### ISSUE TITLE
Clarify readings text

### ISSUE THREAD

**Issue by Iiridayn** [LTUE/call-for-panelists#11]
Per Alicia's email:
1) We talked about adding a question with the end for readings. The question needs to explain that readings are by invitation only, and that it would be an author reading their own work with another author that would be assigned.

**Comment by JKJensen** [comment]
In Profile Form v02, the helper text says:

During a reading, you will be performing one of your own works. You will be paired with another author also reading their work. Note that being given time to perform a reading is by invitation only.

With the additional question:
What book/genre/style would you like to highlight?

<img width="545" alt="Screenshot 2019-08-10 14 43 40" src="https://user-images.githubusercontent.com/5481718/62826709-5271b300-bb7d-11e9-99b3-3619839af835.png">
