### ISSUE TITLE
Clarify moderator role

### ISSUE THREAD

**Issue by Iiridayn** [LTUE/call-for-panelists#12]
Per Alicia's email:
2) We talked about putting the moderator question on a separate page that lists what a moderator is and is not. The design that we talked about was something like "Are you interested in moderating?", if yes, display a new question with a bullet point explanation of duties with a followup question, "If asked to moderate, you will be expected to follow these rules and attend a moderator training. Are you willing to abide by all of the above?" This set of questions is very important, since moderator problems are our biggest issue with panels right now.

**Comment by JKJensen** [comment]
Here's what that moderator section looks like:
<img width="504" alt="Screenshot 2019-08-10 14 45 40" src="https://user-images.githubusercontent.com/5481718/62826722-ba27fe00-bb7d-11e9-8b7b-e8b417d70ad3.png">


If you are interested in being a moderator, please review the moderator tips document, you will be expected to attend a moderator training and follow those guidelines, which include:

1) Starting and ending the panel on time
2) Proper Panel Preparation
3) Asking open ended questions 
4) Ensuring that all panelists are given equal opportunity to speak
5) Keeping the panel interesting and on-topic

------------

This is the moderator tips document to link to:
https://drive.google.com/file/d/1IPo7povWSiXCtzFIY6kGhIvDmrpHVVt9/view

**Comment by Iiridayn** [comment]
@JKJensen Mind if I use "1.", "2." instead of "1)", "2)"? It's easier to use the default browser representation, and browsers don't yet support styling this with parenthesis (except firefox - @counter-style in CSS) without redoing the display logic.

**Comment by JKJensen** [comment]
Go right ahead! Thanks!
