### ISSUE TITLE
Split out "interests" page

### ISSUE THREAD

**Issue by Iiridayn** [LTUE/call-for-panelists#16]
Split from profile page. Has book signing, panels, etc.

Needs "Add Another Presentation/Workshop" which'll be a bother to do w/CSS (hidden checkbox, "Anchor" is a styled label, `input[type=checkbox]:checked + div.thing { display: block }`

**Comment by JKJensen** [comment]
This task can be deleted

**Comment by Iiridayn** [comment]
@JKJensen duplicate of?

**Comment by Iiridayn** [comment]
Duplicate of #27, which has more information.
