### ISSUE TITLE
Social profile links from profile

### ISSUE THREAD

**Issue by Iiridayn** [LTUE/call-for-panelists#18]
Add social profile links for authors - Kate wrote:

> can we add fields for socials where they can put in their handles/URLs? Facebook, Insta, Twitter… both good for vetting mean people but also will give me an idea of how they self promote and how we can harness that self promoting to also promoting LTUE

Follow up by Alex:

> Could it just be a set of arbitrary links (to any social profile or web page)? I've recently discovered a plethora of social networks I hadn't known existed for writers and book lovers. We may never know where people prefer to link to.

**Comment by JKJensen** [comment]
I added this in a section called "Social Media"

<img width="764" alt="Screenshot 2019-08-10 14 54 03" src="https://user-images.githubusercontent.com/5481718/62826763-b3e65180-bb7e-11e9-81ee-0d568a70fea7.png">

Note that I've grabbed the website field from above and brought it down here.

If it's easier if each of these fields is on a separate line, go for that.

**Comment by JKJensen** [comment]
These fields are very much needed this year.
