### ISSUE TITLE
Create a Presentation/Workshop Page

### ISSUE THREAD

**Issue by JKJensen** [LTUE/call-for-panelists#27]
There's some confusion about submitting a presentation that could be smoothed out by having a dedicated presentation page.

Create a Presentations page that looks like this:
![Presentation Workshop](https://user-images.githubusercontent.com/5481718/62826679-c069aa80-bb7c-11e9-809c-8bda051d33e9.jpg)

Gallery Link
https://gallery.io/projects/MCHbtQVoQ2HCZdU-z7PWmckP/files/MCEJu8Y2hyDScTH_dPDur2QHWEm6P0CLACQ

**Comment by JKJensen** [comment]
Here are example links you can use:

Self editing:
https://www.youtube.com/watch?v=AvACVIHOghM

Coloring book:
https://www.youtube.com/watch?v=OYg-qOmAHpE

Language creation:
https://www.youtube.com/watch?v=IQd8QgZgcSU

**Comment by Iiridayn** [comment]
Ideally use https://goodui.org/#43 - progressive disclosure. Bothersome to write w/o JS, but more usable.

**Comment by JKJensen** [comment]
Unneeded now that we're using a google form for Presentations

**Comment by Iiridayn** [comment]
Will this always be unneeded though? If we should want this data to go into the same backend system in the end, we'll probably need this or something similar.

**Comment by JKJensen** [comment]
That's a very good point. I had wanted to create a separate call for presentations and have that open for much longer than just the call for panelists stays open. But... hmm...

Would you be up for creating a Presentations/Workshop submission form this year? (We can reopen this task next year if need be)

**Comment by Iiridayn** [comment]
Sounds like we should maybe have two visually similar systems with the same accounts but different forms, and not reachable from each other since they have different dates. Or perhaps a single buffet style system. Either way, should be very feasible - but not for LTUE 2021 since as I understand we've already sent out the call for presentations, or need to immediately?
