### ISSUE TITLE
Change "suggestions" field wording

### ISSUE THREAD

**Issue by Iiridayn** [LTUE/call-for-panelists#28]
Per Jeff:

> Any chance you can add change the message from:
> “Do you have a presentation or a workshop that you would like to run? If so, please give us a title, description, and a pitch for the programming. We will contact you with possible time slots in November, if your presentation is selected.”
> To:
> “Do you have a presentation or a workshop that you would like to run? If so, please give us a title, description for the program book, and a short pitch to the selection committee. If your presentation is selected, we will contact you with possible time slots in November. Please paste in your responses into these fields.”

**Comment by JKJensen** [comment]
If you do issue #27 , you can delete this task.

**Comment by Iiridayn** [comment]
We've removed suggestions code in c2ffd1705d1f785784a0cd683c016dad2f39a2f2, so closing this.
