### ISSUE TITLE
Change font on checkboxes/radio text to Nunito

### ISSUE THREAD

**Issue by JKJensen** [LTUE/call-for-panelists#32]
Ideally, the fonts alternate between Rajdhani as the question itself with Nunito being the helper text and checkbox/radio text.

Question font: Rajdhani Semibold, 14 pt, spacing 1, #191919
Checkbox/Radio text font: Nunito Regular, 14 pt, spacing 0.5, #191919

Change the checkbox/radio font to Nunito.

Current look:
<img width="587" alt="Screenshot 2019-08-10 14 59 27" src="https://user-images.githubusercontent.com/5481718/62826806-a2517980-bb7f-11e9-8a98-19dce3926920.png">

Change to:
<img width="560" alt="Screenshot 2019-08-10 14 59 06" src="https://user-images.githubusercontent.com/5481718/62826807-ada4a500-bb7f-11e9-945b-24a1ec83e8b6.png">

The 8px of margin between the checkbox/radio button is especially helpful.

Feel free to inspect on the Profile v02 design:
https://gallery.io/projects/MCHbtQVoQ2HCZdU-z7PWmckP/files/MCEJu8Y2hyDScbxpgLldDBncar45N1E0HR4

**Comment by Iiridayn** [comment]
> Ideally, the fonts alternate between Rajdhani as the question itself with Nunito being the helper text and checkbox/radio text.

Would have been great to know up front - would have made the CSS classes much clearer then. Will fix up sometime later :).
