### ISSUE TITLE
Add these five diversity questions

### ISSUE THREAD

**Issue by JKJensen** [LTUE/call-for-panelists#45]
(Optional) What is your ethnicity? (Check all that apply)
☐ White
☐ Black
☐ Asian
☐ Hispanic
☐ Indigenous / Native American
☐ Other ethnicity
☐ Prefer not to say

(Optional) What is your gender identity?
☐ Male
☐ Female
☐ Nonbinary
☐ Other
☐ Prefer not to say

(Optional) Do you identify as any of the following?
☐ Straight / Heterosexual
☐ Lesbian
☐ Gay
☐ Bisexual
☐ Transgender
☐ Queer
☐ Intersex
☐ Asexual
☐ Other
☐ Prefer not to say

(Optional) Do you identify as someone disabled or differently abled, either mentally or physically?
◯ Yes
◯ No
◯ Prefer not to say

(Optional) Do you have any of the following religious affiliations?
☐ Agnostic
☐ Atheist
☐ Buddhist
☐ Catholic
☐ Church of Jesus Christ of Latter-day Saints
☐ General Christian
☐ Hindu
☐ Islamic
☐ Jewish
☐ Other
☐ Prefer not to say

◯ are radio buttons, meaning users can only pick one question. 
☐ are checkboxes that can be selected as many times as they wish.

**Comment by Iiridayn** [comment]
Do these replace "intersectionalities"?

**Comment by JKJensen** [comment]
We’ll still have that question. But the helper text is changing to remove
“intersectionalities”.

Check issue #46 for that change in that helper text.

**Comment by Iiridayn** [comment]
Where do you want it on the form? Just after Personal Info? Social Media? Etc. Check http://iiridayn.info:8013 for the current layout.

**Comment by JKJensen** [comment]
Draw another dividing line after Social media, and put it there. Title that
section “Demographics”

**Comment by Iiridayn** [comment]
When I said adding a field was easy, I meant a free text field :/. These multiselects are amongst the most time-consuming and complicated inputs to add.
